Icosapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("landing.urls"))
]

landing/urls.py
from django.urls import path, include

app_name = "landing"

from . import views
urlpatterns = [
    path("", views.index, name="index"),
    path("select", views.select, name="select"),
    path("contacto", views.contacto, name="contacto"),
    path("desarrollo", views.desarrollo, name="desarrollo"),
    path("pricing", views.pricing, name="pricing"),
    path("message", views.receive_message, name="message"),
    path("business", views.business, name="business"),
    path("web", views.web, name="web"),
    path("mobile", views.mobile, name="mobile"),
]

landing/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    name = models.CharField(max_length=64)
    email = models.EmailField(max_length=64)
    message = models.CharField(max_length=1000)

    def __str__(self):
        return f"{self.name}, {self.email}"

landing/forms.py
from django import forms
from django.forms import ModelForm
from .models import Message

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ('name', 'email', 'message')
        widgets = {
            'message': forms.Textarea()
        }

landing/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect, Http404, HttpResponseBadRequest

from .models import Message
from .forms import MessageForm

# Create your views here.
messageform = MessageForm()

def index(request):
    return render(request, "landing/index.html", {"messageform": messageform, "nombre": "index"})

def select(request):
    return render(request, "landing/seleccion.html", {"messageform": messageform})

def contacto(request):
    return render(request, "landing/contacto.html", {"messageform": messageform})

def desarrollo(request):
    return render(request, "landing/desarrollo.html", {"messageform": messageform})

def pricing(request):
    return render(request, "landing/pricing.html", {"messageform": messageform})

def business(request):
    return render(request, "landing/business.html")

def web(request):
    return render(request, "landing/web.html")

def mobile(request):
    return render(request, "landing/mobile.html")

def receive_message(request):
    next = request.POST.get('next', '/')
    next = next + "#footer"
    form = MessageForm(request.POST)
    if form.is_valid():
        form.save()
    else:
        return HttpResponseBadRequest("Bad Request")
    return HttpResponseRedirect(next)

landing/templates/landing/business.html
{% extends 'landing/layout.html' %}
{% load static %}
{% block header %} ICOS BUSINESS {% endblock %}
{% block header_desc %} Da el siguiente paso en tu negocio con e-commerce <br> Que tus clientes puedan comprar tus productos y servicios <br>
desde tu página web {% endblock %}
{% block body %}
<!-- Three -->
  <section id="three" class="wrapper">
    <div class="inner">
      <header class="align-center">
        <h2>Business</h2>
        <p>Icosaedro crea una página web para tu negocio, en el que podrás administrar</p>
      </header>
          <p><span class="image left"><img src="{% static 'landing/grey.png'%}" alt="Pic 01" style="width: 7em;"/></span>
            <strong>Administra</strong> tu negocio desde la página, <strong>accede</strong> y <strong>visualiza</strong> bases de datos de manera sencilla. Administra tu negocio desde una cuenta especial de administrador.
            Hacemos atractiva tu página con interfaces interactivas para sus clientes.
            Tenemos una variedad de plantillas de las cuales elegir, sin embargo, puedes hacer los cambios que quieras para que tu aplicación quede tal y como la imaginaste.</p>
          <div class="image right">
              <img src="{% static 'landing/blue.png' %}" alt="Pic 02" style="width: 10em;"/>
          </div>
          <p>Revisamos contigo la integración de tu aplicación de principio a fin. Nuestro equipo de desarrolladores te escucha desde el primer momento, para que el diseño y la funcionalidad sean uno mismo.
          Durante el proceso, se le mostrarán los resultados para que modifique lo que quiera, y esté completamente satisfecho con el resultado. <br>
          Interactúa con nuestro equipo por correo y llamadas con el fin de ajustar presupuestos y planear el despliegue final. ¡Hacemos lo que nos pidas!</p>
          <div class="table-wrapper">
										<table class="alt">
											<thead>
												<tr>
                          <th>Nombre</th>
                          <th>Descripción</th>
                          <th>Precio</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td>BASIC</td>
													<td>Ideal para microempresas. Tranferencia de datos
                          ilimitada durante 550 horas, 512 MB de RAM, base de datos elemental. </td>
													<td>3,500.00</td>
												</tr>
												<tr>
													<td>DREAMER</td>
													<td>Ideal para empresas pequeñas que están en constante crecimiento. Tranferencia de datos ilimitada
                          , bases de datos de hasta 10 M de filas, 512 GB de Ram, y hasta 20 cuentas de empleado. </td>
													<td>7,500.00</td>
												</tr>
												<tr>
													<td>ROCKET</td>
													<td>Ideal para empresas medianas. Transferencia de datos ilimitados, hasta 4GB de RAM,
                          64GB de almacenamiento, y hasta 120 cuentas de empleado. </td>
													<td>15,000.00</td>
												</tr>
												<tr>
													<td>ICOSAEDRO</td>
													<td>Ideal para empresas grandes. Todo ilimitado, todo a tu medida.</td>
													<td>35,000.00</td>
												</tr>
											</tbody>
										</table>
									</div>

          <div class="align-center">
            <p>Contáctanos ahora mismo, para comenzar con el proceso </p>
            <a href="{% url 'landing:contacto' %}" class="button">Siguiente</a>
          </div>
    </div>
  </section>
  {% include "landing/footer.html" %}
{% endblock %}

landing/templates/landing/contacto.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>Icosaedro</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'landing/main.css' %}"/>
		<link rel="icon" href="{% static 'landing/icosahedron.png' %}" type="image/icon type">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	</head>
	<body>

    <!-- Three -->
        <section id="three" class="wrapper">
            <div class="inner">
                <header class="align-center">
                    <h2>Comúnicate con nosotros</h2>
                    <p>Asesoría Continua</p>
                </header>
                <div class="image left">
                    <img src="{% static 'landing/grey.png' %}" alt="Pic 01" style="width: 8em;"/>
                </div>
                <p>Revisamos contigo la integración de tu aplicación de principio a fin. Nuestro equipo de desarrolladores te escucha desde el primer momento para que diseño y funcionalidad sean uno mismo.</p>

                <div class="image round right">
                    <img src="{% static 'landing/blue.png' %}" alt="Pic 02" style="width: 25em;"/>
                </div>
                <p>Interactúa con nuestro equipo por correo y llamadas con el fin de ajustar presupuestos y planear el despliegue final. ¡Hacemos lo que nos pidas!</p>
                <a href="{% url 'landing:desarrollo' %}" class="button">Siguiente</a>
            </div>
            
        </section>

    <!-- Footer -->
        {% include "landing/footer.html" %}
	</body>
	<script src="{% static 'landing/index.js' %}"></script>
    <script src="https://kit.fontawesome.com/c658774e7e.js" crossorigin="anonymous"></script>
</html>

landing/templates/landing/desarrollo.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>Icosaedro</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'landing/main.css' %}"/>
		<link rel="icon" href="{% static 'landing/icosahedron.png' %}" type="image/icon type">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	</head>
	<body>

    <!-- Three -->
        <section id="three" class="wrapper">
            <div class="inner">
                <header class="align-center">
                    <h2>Revisa el Desarrollo</h2>
                    <p>Observa el progreso y ajusta a tu gusto</p>
                </header>
                <div class="image left">
                    <img src="{% static 'landing/purple.png' %}" alt="Pic 01" style="width: 10em;"/>
                </div>
                <p>Recibe datos de desarrolladores sobre el progreso de tu páginade manera continua. Danos tus recomendaciones y sugerencias en cualquier etapa de avance.</p>

                <div class="image right">
                    <img src="{% static 'landing/red.png' %}" alt="Pic 02" style="width: 30em;"/>
                </div>
                <p><strong>Personaliza</strong> tus apliaciones y diferénciate de la competencia. <br>
                    Elige estilos, experiencia de usuario y flujo de clientes.
                </p>
                <p>Nos comprometemos con lo prometido, hacemos <strong>Diseño a la Medida</strong> de principio a fin. <br>
                Te entregamos tu producto y continuamos con el <strong>Servicio de Mantenimiento</strong> acordado.
                </p>
                <a href="{% url 'landing:pricing' %}" class="button">Precios Mantenimiento</a>
            </div>
        </section>

    <!-- Footer -->
        {% include "landing/footer.html" %}
	</body>
	<script src="{% static 'landing/index.js' %}"></script>
    <script src="https://kit.fontawesome.com/c658774e7e.js" crossorigin="anonymous"></script>
</html>

landing/templates/landing/footer.html
<footer id="footer">
    <div class="inner">

        <h3>Contacto</h3>
        <form id ="message-form" action="{% url 'landing:message' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.path }}">
            <div class="field half first">
                <label for="name">Nombre</label>
                {{ messageform.name }}
            </div>
            <div class="field half">
                <label for="email">Email</label>
                {{ messageform.email }}
            </div>
            <div class="field">
                <label for="message">Cuéntanos lo que sea</label>
                {{ messageform.message }}
            </div>
            <ul class="actions">
                <li><input id="message-button" value="Enviar Mensaje" class="button alt" type="submit"></li>
            </ul>
        </form>

        <div class="copyright">
            Guadalajara, Jalisco, México.
        </div>

    </div>
</footer>

landing/templates/landing/index.html
{% extends "landing/layout.html" %}
{% load static %}
{% block body %}

<!-- Header -->
<header id="header">
	<div class="inner">
		<a onClick="smoothScroll('#banner')" class="logo"><strong>ICOSAEDRO</strong> Application</a>
		<nav id="nav">
			<a onClick="smoothScroll('#information')">Información</a>
			<a onClick="smoothScroll('#products')">Productos</a>
			<a onClick="smoothScroll('#tech')">Tecnología</a>
			<a onClick="smoothScroll('#footer')">Contacto</a>
		</nav>
		<a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
	</div>
</header>

<!-- Banner -->
	<section id="banner">
		<div class="inner">
			<header>
				<h1>ICOSAEDRO <img id="icoslogo" src="{% static 'landing/icosahedron.png' %}" class="zoom"></h1>
				<h3>Cloud applications, on demand.</h3>
			</header>

			<div class="flex ">

				<div>
					<div class="zoom">
					<a href="{% url 'landing:business' %}" style="text-decoration: none;">
					<span class="icon fa-briefcase"></span>
					<h3>Business</h3>
					<p>Interfaz web de negocios.</p>
					</a>
					</div>
				</div>

				<div>
					<div class="zoom">
					<a href="{% url 'landing:web' %}" style="text-decoration: none;">
					<span class="icon fa-code"></span>
					<h3>Web</h3>
					<p>Desarrollo web en la nube.</p>
					</a>
					</div>
				</div>

				<div>
					<div class="zoom">
						<a href="{% url 'landing:mobile' %}" style="text-decoration: none;">
						<span class="icon fa-mobile"></span>
						<h3>Mobile</h3>
						<p>Apps móviles a la medida.</p>
						</a>
					</div>
				</div>

			</div>

			<footer id="start">
				<a href="{% url 'landing:select' %}" class="button">Empezar</a>
			</footer>
		</div>
	</section>

	<!-- Info -->
	<section id="information" class="wrapper">
		<div class="inner">
			<hr>
			<header class="align-center">
				<h2>Nuestros Servicios</h2>
				<p>Información</p>
			</header>

		<!-- Intro -->
			<div class="row">
				<section class="6u 12u$(medium)">
					<h2>Desarrollo de Software</h2>
					<p>Hacemos <strong>Cloud Applications:</strong> sistemas remotos basados en la web, sumamente sencillos de escalar y hechos a la medida, donde el mantenimiento es mínimo. <br><strong>ICOSAPP</strong> es una iniciativa de desarrolladores enfocada en la técnica, en especial para garantizar calidad de operación y seguridad informática.</p>
				</section>
				<section class="3u 6u(medium) 12u$(small)">
					<h3>Servicios Web</h3>
					<p>Permiten la conectividad entre usuarios y transacciones. Todas nuestras aplicaciones integran una <strong>REST API:</strong> una interfaz para que tu aplicación esté conectada de manera segura y eficiente.</p>
				</section>
				<section class="3u$ 6u$(medium) 12u$(small)">
					<h3>Deployment</h3>
					<p>Nosotros nos encargamos de todo. Manejamos por ti los nombres de <strong>dominio</strong>, <strong>encripción</strong> de transacciones, arquitectura de <strong>bases de datos</strong>, ajustes de <strong>servidores</strong> y <strong>publicación</strong>.</p>
				</section>
				<section>
					<h2>¿Qué hago?</h2>
					<div class="flex">
						<div class="stepdiv zoom">
							<a href="{% url 'landing:select' %}" class="stepa">
							<img src="{% static 'landing/step1.png' %}" alt="" class="stepimg">
							<h3>Encuentra lo que buscas</h3>
							<p>Navegando en la página, encuentra las opciones que satisfagan tus nececidades. <br> También puedes dejar tus datos de contacto con tus dados en el apartado de contacto.</p>
							</a>
						</div>
						<div class="stepdiv zoom">
							<a href="{% url 'landing:contacto' %}" class="stepa">
							<img src="{% static 'landing/step2.png' %}" alt="" class="stepimg">
							<h3>Comunícate con nosotros</h3>
							<p>Una vez en contacto con nuestro equipo, te haremos saber lo necesario para poner en marcha tu presencia en internet. <br> Te ayudamos a identificar qué recursos necesitas.</p>
							</a>
						</div>
						<div class="stepdiv zoom">
							<a href="{% url 'landing:desarrollo' %}" class="stepa">
							<img src="{% static 'landing/step3.png' %}" alt="" class="stepimg">
							<h3>Revisa continuamente el desarrollo</h3>
							<p>Puedes revisar el progreso de tu pedido directamente con los desarrolladores. <br> Ve los cambios suceder en tiempo real.</p>
							</a>
						</div>
					</div>
				</section>
			</div>
		</div>

		<div class="flex techel">

		</div>

	</section>

	<hr>
<!-- Two -->
	<section id="products" class="wrapper align-center">
		<div class="inner">
			<div class="flex flex-2">
				<article>
					<div class>
						<img src="{% static 'landing/laptop.png' %}" alt="Pic 01"/>
					</div>
					<header>
						<h3>Sitios Web<br /> Integrados</h3>
					</header>
					<p>Elige exactamente los recursos que necesitas.<br />Seguridad informática desde producción.<br />Cloud computing escalable.</p>
				</article>
				<article>
					<div class>
						<img src="{% static 'landing/phone.png' %}" alt="Pic 02" />
					</div>
					<header>
						<h3>Aplicaciones móviles<br /> Híbridas</h3>
					</header>
					<p>Compatibilidad iOS y Android.<br />Aplicaciones responsivas y conectadas a la red.<br />Desarrollo económico en plataformas nativas.</p>
				</article>
			</div>
		</div>
	</section>

<!-- Three -->
	<section id="three" class="wrapper align-center">
		<div class="inner">
			<div class="flex flex-2">
				<article>
					<div class="image round">
						<img src="{% static 'landing/icobriefcase.png' %}" alt="Pic 01" style="width: 100%; float: center;"/>
					</div>
					<header>
						<h3>Administración<br /> Accesible</h3>
					</header>
					<p>Vinculamos bases de datos directamente a interfaces administrativas.<br />Genera y descarga facturas de inmediato.<br />Personaliza tu aplicación para llevarla al siguiente nivel.</p>
				</article>
				<article>
					<div class>
						<img src="{% static 'landing/shopping.png' %}" alt="Pic 02" style="width: 21.5%; float: center;"/>
					</div>
					<header>
						<h3>E-Commerce<br /> Escalable</h3>
					</header>
					<p>Acepta una variedad de servicios de pago.<br />Permite pagos al instante o suscripciones.<br />Recibe fondos directo en tu cuenta.</p>
				</article>
			</div>
		</div>
	</section>

<!--Technologies-->
<section id="tech" class="wrapper align-center">
	<div class="inner">
		<hr>
		<header>
			<h2>Tecnología</h2>
			<p>Desarrollamos con la tecnología más moderna para brindarte un servicio de software con poder y seguridad. <br>
			Diseñamos arquitecturas una sola vez para el soporte de todas tus aplicaciones.
			</p>
		</header>
		<hr>
		<div class="flex">
			<div class="techel flex">
				<div class="zoom">
					<span class="icontech fa-html5"></span>
					<h3>HTML5</h3>
					<p>Diseño web personalizado.</p>
				</div>
				<div class="zoom">
					<span class="icontech fa-lock"></span>
					<h3>SSL</h3>
					<p>Dale confianza a tus clientes.</p>
				</div>
				<div class="zoom">
					<span class="icontech fa-js"></span>
					<h3>Javscript</h3>
					<p>Sitios dinámicos.</p>
				</div>
				<div class="zoom">
					<span class="icontech fa-python"></span>
					<h3>Python</h3>
					<p>Servidores multipropósito.</p>
				</div>
				<div class="zoom">
					<span class="icontech fa-database"></span>
					<h3>PostgreSQL</h3>
					<p>Almacenamiento de datos seguro.</p>
				</div>
				<div class="zoom">
					<span class="icontech fa-apple"></span>
					<h3>iOS</h3>
					<p>Desarrollo híbrido y económico.</p>
				</div>
				<div class="zoom">
					<span class="icontech fa-android"></span>
					<h3>Android</h3>
					<p>Aplicaciones conectadas y veloces.</p>
				</div>
				<div class="zoom">
					<span class="icontech fa-server"></span>
					<h3>Gunicorn</h3>
					<p>Servidores que escalan según el tráfico.</p>
				</div>
				<div class="zoom">
					<span class="icontech fa-react"></span>
					<h3>React</h3>
					<p>La mejor experiencia de usuario.</p>
				</div>
				<div class="zoom">
					<span class="icontech fa-stripe"></span>
					<h3>Stripe</h3>
					<p>Acepta pagos de todo tipo, de todo el mundo.</p>
				</div>


			</div>
		</div>
	</div>
</section>
<!-- Footer -->
{% include "landing/footer.html" %}
{% endblock %}

landing/templates/landing/layout.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>Icosaedro</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta name="description" content="Desarrollo de sitios web y aplicaciones en la nube.">
		<meta name="keywords" content="Sitios Web Aplicaciones Negocios Nube Cloud Páginas Web">
			<link rel="stylesheet" href="{% static 'landing/main.css' %}"/>
			{% block css %}{% endblock %}
		<link rel="icon" href="{% static 'landing/icosahedron.png' %}" type="image/icon type">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	</head>
	<body>
		{% if nombre != "index" %}
		<!-- Header -->
			<section id="banner">
					<div class="inner">
							<header>
									<h1>{% block header%} ICOS MOBILE {% endblock %} <img id="icoslogo" src="{% static 'landing/icosahedron.png' %}" class="zoom"></h1>
									<h3>{% block header_desc %}Desarrolla una aplicación móvil para tu negocio <br> Para Andorid, iPhone, o Nokia.{% endblock %}</h3>
							</header>
					</div>
			</section>
			   <hr>
			{% endif %}
      {% block body %}
			{% endblock %}
	</body>
	<script src="{% static 'landing/index.js' %}"></script>
	<script src="https://kit.fontawesome.com/c658774e7e.js" crossorigin="anonymous"></script>
</html>

landing/templates/landing/mobile.html
{% extends 'landing/layout.html' %}
{% load static %}
{% block header %} ICOS MOBILE {% endblock %}
{% block header_desc %} Desarrolla una aplicación móvil para tu negocio <br>Aplicaciones híbridas, que funcionan en cualquier dispositivo {% endblock %}
{% block body %}
		<!-- Three -->
			<section id="three" class="wrapper">
				<div class="inner">
					<header class="align-center">
						<h2>Mobile</h2>
						<p>Icosaedro te crea una aplicación móvil resposiva para tu negocio, con enfoque en la experiencia del usuario.<br>
						Procesa compras, accede a mapas, y mucho más. Icosaedro vuelve tus sueños realidad.</p>
					</header>
							<p><span class="image left"><img src="{% static 'landing/red.png'%}" alt="Pic 03" style="width: 14em;"/></span>Creamos tu aplicación tal y como la imaginas</p>
							<p> Icosaedro ofrece todo tipo de implementaciones para tu aplicación; desde e-commerce, hasta mapas interactivos. Lo que se te ocurra, lo podemos. <br>
								Tenemos una variedad de plantillas de las cuales elegir, sin embargo, puedes hacer los cambios que quieras para que tu aplicación quede tal y como la imaginaste.
							Icosahedro ofrece apliaciones híbridas, por lo que podrá usar la apliación desde cualquier dispositivo móvil.</p>
              <div class="image left">
                  <img src="{% static 'landing/purple.png' %}" alt="Pic 01" style="width: 16em;"/>
              </div>
              <p>Revisamos contigo la integración de tu aplicación de principio a fin. Nuestro equipo de desarrolladores te escucha desde el primer momento, para que el diseño y la funcionalidad sean uno mismo.
							Durante el proceso, se le mostrarán los resultados para que modifique lo que quiera, y esté completamente satisfecho con el resultado. <br>
							Interactúa con nuestro equipo por correo y llamadas con el fin de ajustar presupuestos y planear el despliegue final. ¡Hacemos lo que nos pidas!</p>
								<div class="table-wrapper">
													<table class="alt">
														<thead>
															<tr>
																<th>Nombre</th>
																<th>Descripción</th>
																<th>Precio</th>
															</tr>
														</thead>
														<tbody>
															<tr>
																<td>BASIC</td>
																<td>Ideal para microempresas. Aplicación disponible en la App Store y Google Play, diseño básico adaptado a móvil. </td>
																<td>3,500.00</td>
															</tr>
															<tr>
																<td>DREAMER</td>
																<td>Ideal para empresas pequeñas que están en constante crecimiento.
																	Aplicación disponible en la App Store y Google Play, diseño a la medida y acceso a las herramientas del móvil.  </td>
																<td>7,500.00</td>
															</tr>
															<tr>
																<td>ICOSAEDRO</td>
																<td>Ideal para empresas grandes. Todo ilimitado, todo a tu medida.</td>
																<td>15,000.00</td>
															</tr>
														</tbody>
													</table>
												</div>
							<div class="align-center">
              	<p>Contáctanos ahora mismo, para comenzar con el proceso </p>
								<a href="{% url 'landing:contacto' %}" class="button">Siguiente</a>
							</div>
				</div>
			</section>
		{% include "landing/footer.html" %}
{% endblock %}

landing/templates/landing/seleccion.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>Icosaedro</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'landing/main.css' %}"/>
		<link rel="icon" href="{% static 'landing/icosahedron.png' %}" type="image/icon type">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	</head>
	<body>

    <!-- Three -->
        <section id="three" class="wrapper">
            <div class="inner">
                <header class="align-center">
                    <h2>Descubre soluciones para ti</h2>
                    <p>Nuestros Servicios</p>
                </header>
                <div class="image left">
                    <img src="{% static 'landing/icosahedron.png' %}" alt="Pic 01" style="width: 8em;"/>
                </div>
                <p><strong>Sitios Web</strong> integrados, estéticos y funcionales. <br>Encuéntrate con poderosos servidores, almacenamiento de archivos y bases de datos en la nube, así como un <strong>E-Commerce</strong> robusto.</p>

                <div class="image right">
                    <img src="{% static 'landing/orange.png' %}" alt="Pic 02" style="width: 25em;"/>
                </div>
                <p><strong>Aplicaciones móviles</strong> responsivas, con enfoque en la experiencia de usuario. <br>
                    Procesa compras, accede a mapas, cámara y mucho más del potencial de los dispositivos móviles.
                </p>
                <p>Responde a lo que necesita tu negocio con nuestras interfaces <strong>Business</strong>. <br>
                Elige exactamente cómo quieres que tus empleados alimenten tu sistema y recibe información detallada sobre ventas, inventarios, desempeño y más.
                </p>
                <a href="{% url 'landing:contacto' %}" class="button">Siguiente</a>
            </div>
        </section>

    <!-- Footer -->
        {% include "landing/footer.html" %}
	</body>
	<script src="{% static 'landing/index.js' %}"></script>
    <script src="https://kit.fontawesome.com/c658774e7e.js" crossorigin="anonymous"></script>
</html>

landing/templates/landing/web.html
{% extends 'landing/layout.html'%}
{% load static %}
{% block header %} ICOS WEB {% endblock %}
{% block header_desc %} Crea una página web para tu negocio. {% endblock %}
{% block body %}
<!-- Three -->
  <section id="three" class="wrapper">
    <div class="inner">
      <header class="align-center">
          <h2>Web</h2>
        <p>Icosaedro te crea una página web para tu negocio. Ideal si tu +</p>
      </header>
          <p><span class="image left"><img src="{% static 'landing/orange.png'%}" alt="Pic 03" style="width: 7em;"/></span>Creamos tu aplicación tal y como la imaginas</p>
          <p> Icosaedro ofrece todo tipo de implementaciones para tu aplicación; desde e-commerce, hasta mapas interactivos. Lo que se te ocurra, lo podemos. <br>
            Tenemos una variedad de plantillas de las cuales elegir, sin embargo, puedes hacer los cambios que quieras para que tu aplicación quede tal y como la imaginaste.</p>
          <div class="image right">
              <img src="{% static 'landing/web.png' %}" alt="Pic 01" style="width: 14em;"/>
          </div>
          <p>Revisamos contigo la integración de tu página web, de principio a fin. Nuestro equipo de desarrolladores te escucha desde el primer momento, para que el diseño y la funcionalidad sean uno mismo.
          Durante el proceso, se le mostrarán los resultados para que modifique lo que quiera, y esté completamente satisfecho con el resultado. <br>
          Interactúa con nuestro equipo por correo y llamadas con el fin de ajustar presupuestos y planear el despliegue final. ¡Hacemos lo que nos pidas!</p>
          <div class="table-wrapper">
                    <table class="alt">
                      <thead>
                        <tr>
                          <th>Nombre</th>
                          <th>Descripción</th>
                          <th>Precio</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>BASIC</td>
                          <td>Ideal para microempresas. Estética sencilla y transacciones sencillas. </td>
                          <td>3,500.00</td>
                        </tr>
                        <tr>
                          <td>DREAMER</td>
                          <td>Ideal para empresas pequeñas que están en constante crecimiento. Diseño a la medida, e-commerce básico. </td>
                          <td>7,500.00</td>
                        </tr>
                        <tr>
                          <td>ROCKET</td>
                          <td>Ideal para empresas medianas. Diseño a la medida, e-commerce y elementos dinámicos e interactivos. </td>
                          <td>15,000.00</td>
                        </tr>
                        <tr>
                          <td>ICOSAEDRO</td>
                          <td>Ideal para empresas grandes. Todo ilimitado, todo a tu medida.</td>
                          <td>35,000.00</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
          <div class="align-center">
            <p>Contáctanos ahora mismo, para comenzar con el proceso </p>
            <a href="{% url 'landing:contacto' %}" class="button">Siguiente</a>
          </div>
    </div>
  </section>
{% endblock %}